/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itpm.finance_management;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Prabhashwara
 */
public class IncomeManage2 extends javax.swing.JFrame {

    int quWater, quAvo, quMix, quMan, quWood;
    double tot;
    
    /**
     * Creates new form CostManage
     */
    public IncomeManage2() {
        initComponents();
         this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    private void getIncome(String dates) {
        Connection con = DBConnection.getConnection();
        
        String query1 = "select soldQuantity from soldItem where dates = '" + dates + "' and itemName='watermelon'";
        String query2 = "select soldQuantity from soldItem where dates = '" + dates + "' and itemName='woodapple'";
        String query3 = "select soldQuantity from soldItem where dates = '" + dates + "' and itemName='mango'";
        String query4 = "select soldQuantity from soldItem where dates = '" + dates + "' and itemName='avocardo'";
        String query5 = "select soldQuantity from soldItem where dates = '" + dates + "' and itemName='mixfruit'";
        
        try {
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(query1);
            
            Statement statement2 = con.createStatement();
            ResultSet rs2 = statement2.executeQuery(query2);
            
            Statement statement3 = con.createStatement();
            ResultSet rs3 = statement3.executeQuery(query3);
            
            Statement statement4 = con.createStatement();
            ResultSet rs4 = statement4.executeQuery(query4);
            
            Statement statement5 = con.createStatement();
            ResultSet rs5 = statement5.executeQuery(query5);
            
            while(rs.next()) {
                quWater = rs.getInt("soldQuantity");
            }
            while(rs2.next()) {
                quAvo = rs2.getInt("soldQuantity");
            }
            while(rs3.next()) {
                quMix = rs3.getInt("soldQuantity");
            }
            while(rs4.next()) {
                quMan = rs4.getInt("soldQuantity");
            }
            while(rs5.next()) {
                quWood = rs5.getInt("soldQuantity");
            }
        } catch(SQLException e) {
            System.out.println(e);
        }
        
        txtAvocada.setText(String.valueOf(quAvo));
        txt_Mix.setText(String.valueOf(quMix));
        txt_man.setText(String.valueOf(quMan));
        txt_water.setText(String.valueOf(quWater));
        txt_wood.setText(String.valueOf(quWood));
        
        prAvo.setText("130.00");
        prmx.setText("150.00");
        prma.setText("110.00");
        prwo.setText("120.00");
        prwa.setText("100.00");
        
        toav.setText(String.valueOf(quAvo * 130.00));
        tomx.setText(String.valueOf(quMix * 150.00));
        toma.setText(String.valueOf(quMan * 110.00));
        towo.setText(String.valueOf(quWood * 120.00));
        towa.setText(String.valueOf(quWater * 100.00));
        
        toto.setText(String.valueOf( (quAvo * 130.00) + (quMix * 150.00) + (quMan * 110.00) + (quWood * 120.00) + (quWater * 100.00) ));
        
        tot = (quAvo * 130.00) + (quMix * 150.00) + (quMan * 110.00) + (quWood * 120.00) + (quWater * 100.00);
    }
    
    private void viewIncome(String dates) {
        getIncome(dates);
    }
    
    private void saveIncome(String dates) {
        
        double t =  Double.parseDouble(toto.getText());

        Connection connection = DBConnection.getConnection();

        String query = "insert into totalIncome(dates, income) values('" + dates + "', " + t + ")";

        try {
            Statement statement = connection.createStatement();
            int x = statement.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data saved successfully");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data is Already saved");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_income = new javax.swing.JButton();
        btn_cost = new javax.swing.JButton();
        btn_profit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAvocada = new javax.swing.JLabel();
        prAvo = new javax.swing.JLabel();
        toav = new javax.swing.JLabel();
        txt_Mix = new javax.swing.JLabel();
        prmx = new javax.swing.JLabel();
        tomx = new javax.swing.JLabel();
        txt_man = new javax.swing.JLabel();
        prma = new javax.swing.JLabel();
        toma = new javax.swing.JLabel();
        txt_wood = new javax.swing.JLabel();
        prwo = new javax.swing.JLabel();
        towo = new javax.swing.JLabel();
        txt_water = new javax.swing.JLabel();
        prwa = new javax.swing.JLabel();
        towa = new javax.swing.JLabel();
        toto = new javax.swing.JLabel();
        jDates = new com.toedter.calendar.JDateChooser();
        btn_view = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_income.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_income.setText("Income");
        btn_income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_incomeActionPerformed(evt);
            }
        });

        btn_cost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cost.setText("Cost");
        btn_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_costActionPerformed(evt);
            }
        });

        btn_profit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_profit.setText("Profit");
        btn_profit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_income, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_profit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btn_income, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_profit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sumudu Juice Bar");
        jLabel1.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Item");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Avocado");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mix fruit");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Mango");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Wood Apple");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quantity");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Price of One Item");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Watermelon");

        txtAvocada.setBackground(new java.awt.Color(255, 255, 255));
        txtAvocada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAvocada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAvocada.setOpaque(true);

        prAvo.setBackground(new java.awt.Color(255, 255, 255));
        prAvo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prAvo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prAvo.setOpaque(true);

        toav.setBackground(new java.awt.Color(255, 255, 255));
        toav.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toav.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toav.setOpaque(true);

        txt_Mix.setBackground(new java.awt.Color(255, 255, 255));
        txt_Mix.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Mix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Mix.setOpaque(true);

        prmx.setBackground(new java.awt.Color(255, 255, 255));
        prmx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prmx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prmx.setOpaque(true);

        tomx.setBackground(new java.awt.Color(255, 255, 255));
        tomx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tomx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tomx.setOpaque(true);

        txt_man.setBackground(new java.awt.Color(255, 255, 255));
        txt_man.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_man.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_man.setOpaque(true);

        prma.setBackground(new java.awt.Color(255, 255, 255));
        prma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prma.setOpaque(true);

        toma.setBackground(new java.awt.Color(255, 255, 255));
        toma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toma.setOpaque(true);

        txt_wood.setBackground(new java.awt.Color(255, 255, 255));
        txt_wood.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_wood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_wood.setOpaque(true);

        prwo.setBackground(new java.awt.Color(255, 255, 255));
        prwo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prwo.setOpaque(true);

        towo.setBackground(new java.awt.Color(255, 255, 255));
        towo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        towo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        towo.setOpaque(true);

        txt_water.setBackground(new java.awt.Color(255, 255, 255));
        txt_water.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_water.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_water.setOpaque(true);

        prwa.setBackground(new java.awt.Color(255, 255, 255));
        prwa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prwa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prwa.setOpaque(true);

        towa.setBackground(new java.awt.Color(255, 255, 255));
        towa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        towa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        towa.setOpaque(true);

        toto.setBackground(new java.awt.Color(255, 255, 255));
        toto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toto.setOpaque(true);

        btn_view.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDates, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_view))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAvocada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Mix, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_man, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_wood, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_water, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prAvo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prmx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prwo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prwa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(towa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(towo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(toma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tomx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(toav, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(toto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDates, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_view))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvocada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prAvo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Mix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prmx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tomx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_man, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_wood, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prwo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(towo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_water, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prwa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(towa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(toto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(0, 93, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String vPDate = df.format(jDates.getDate());
            viewIncome(vPDate);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Date Field is empty");
            System.out.println(e);
        }
        //SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        //String vPDate = df.format(jDates.getDate());
        //viewIncome(vPDate);
    }//GEN-LAST:event_btn_viewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String vPDate = df.format(jDates.getDate());
            saveIncome(vPDate);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Date Field is empty");
            System.out.println(e);
        }
        //SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        //String vPDate = df.format(jDates.getDate());
        //saveIncome(vPDate);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_costActionPerformed
        // TODO add your handling code here:
        CostManage c = new CostManage();
        c.setVisible(true);
       dispose();
    }//GEN-LAST:event_btn_costActionPerformed

    private void btn_profitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profitActionPerformed
        // TODO add your handling code here:
        Profit profit = new Profit();
        profit.setVisible(true);
       dispose();
    }//GEN-LAST:event_btn_profitActionPerformed

    private void btn_incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_incomeActionPerformed
        // TODO add your handling code here:
            IncomeManage2 income = new IncomeManage2();
        income.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_incomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncomeManage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncomeManage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncomeManage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncomeManage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncomeManage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cost;
    private javax.swing.JButton btn_income;
    private javax.swing.JButton btn_profit;
    private javax.swing.JButton btn_view;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel prAvo;
    private javax.swing.JLabel prma;
    private javax.swing.JLabel prmx;
    private javax.swing.JLabel prwa;
    private javax.swing.JLabel prwo;
    private javax.swing.JLabel toav;
    private javax.swing.JLabel toma;
    private javax.swing.JLabel tomx;
    private javax.swing.JLabel toto;
    private javax.swing.JLabel towa;
    private javax.swing.JLabel towo;
    private javax.swing.JLabel txtAvocada;
    private javax.swing.JLabel txt_Mix;
    private javax.swing.JLabel txt_man;
    private javax.swing.JLabel txt_water;
    private javax.swing.JLabel txt_wood;
    // End of variables declaration//GEN-END:variables
}
